spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: root
